export enum ErrorCode {
  // category
  CATEGORY_NOT_FOUND = 'CATEGORY_NOT_FOUND',
  CATEGORY_POSITION_CONFLICT = 'CATEGORY_POSITION_CONFLICT ',
  CATEGORY_POSITION_NOT_FOUND = 'CATEGORY_POSITION_NOT_FOUND ',
}
